### ISSUE TITLE
Error in playback mode [json/http]

### ISSUE THREAD

**Issue by viniciusbarbosa** [CityPulse/Data-Stream-Generator#1]
Hello!
Congratulations on your code! It's helping me a lot!
While I run the "playback" mode encounter the following error:

`Playback Configuration:
Target URI: http://localhost
Playback Speed: 1.0
Playback Mode: JSON/HTTP
Playback File: /home/vinicius/cpa/target/testeTemperatura.ttl
Validating and reading dataset ...[Read 12 points, starting playback ...java.lang.NullPointerException
    at com.ericsson.research.iot.citypulse.CityPulseDataPlayback.oldestPointIndex(CityPulseDataPlayback.java:208)
    at com.ericsson.research.iot.citypulse.CityPulseDataPlayback.playBackData(CityPulseDataPlayback.java:103)
    at com.ericsson.research.iot.citypulse.CityPulseInterface.main(CityPulseInterface.java:323)
root@vinicius-vm-3:/home/vinicius/cpa/target# 
`

What should I enter in Target URL to work the JSON / HTTP option?
Sorry my english.
Thanks

**Comment by karapant** [comment]
Hi, thanks for reporting this, can you please send me the file you are trying to playback ?

**Comment by viniciusbarbosa** [comment]
Thanks for the feedback.
I need a lot of your tool.
I'm trying to connect it to Apache Kafka.
I put the file in error in a directory so you can see it (http://projete.me/TemperaturaCarangola.ttl).

In the URL attribute, I must put the URL of the site that will be powered by the data generated?

Thank you again

**Comment by viniciusbarbosa** [comment]
Solved. I changed the code.

**Comment by P00HP00H** [comment]
Hello!
I made a ttl file following your code. 
However, I can't playback the ttl file. Can you tell me how to play it?
Thanks.
